CREATE TABLE public.car (
	car_id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	car_brand varchar NULL,
	vin_code varchar NULL,
	car_color varchar NULL,
	car_model varchar NULL,
	release_year date NULL,
	engine_type varchar NULL,
	fuel_type varchar NULL,
	engine_capacity varchar NULL,
	transmission_type varchar NULL,
	user_id serial4 NOT NULL,
	CONSTRAINT car_pkey PRIMARY KEY (car_id),
	CONSTRAINT car_unique UNIQUE (user_id)
);

CREATE TABLE public.service_history (
	car_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	motor_oil varchar NOT NULL,
	air_filter varchar NOT NULL,
	transmission_oil varchar NULL,
	cabin_filter varchar NULL,
	oil_filter varchar NULL,
	fuel_filter varchar NULL,
	mileage varchar NULL,
	user_id serial4 NOT NULL,
	CONSTRAINT service_history_pkey PRIMARY KEY (car_id)
);

CREATE TABLE public.break_history (
	car_id int4 GENERATED BY DEFAULT AS IDENTITY( MINVALUE 0 NO MAXVALUE START 0 NO CYCLE) NOT NULL,
	break varchar NOT NULL,
	error_code varchar NOT NULL,
	user_id serial4 NOT NULL,
	CONSTRAINT break_history_pkey PRIMARY KEY (car_id),
	CONSTRAINT fk_break_history_car FOREIGN KEY (car_id) REFERENCES public.car(car_id),
	CONSTRAINT fk_car FOREIGN KEY (car_id) REFERENCES public.car(car_id)
);

CREATE TABLE public.garage (
	car_id int4 GENERATED BY DEFAULT AS IDENTITY( MINVALUE 0 NO MAXVALUE START 0 NO CYCLE) NOT NULL,
	cars varchar NOT NULL,
	user_id serial4 NOT NULL,
	CONSTRAINT garage_pkey PRIMARY KEY (car_id)
);

CREATE TABLE public.users (
	user_id serial4 NOT NULL,
	username varchar NOT NULL,
	password_hash varchar NULL,
	full_name varchar NOT NULL,
	email varchar NOT NULL,
	creation_data timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ID" PRIMARY KEY (user_id),
	CONSTRAINT users_unique UNIQUE (email)
);
